### ISSUE TITLE
Rearrange the flex items

### ISSUE THREAD

**Issue by imbipulkumar** [danieljcode/COVID-19tracker#15]
A positive User eXperience can be achieved by attaining the focus of visitors to Recovered stats preceded by Current Cases and followed by Current Deaths.

![Rearranged flex item](https://user-images.githubusercontent.com/31007652/95738687-431d5680-0ca7-11eb-9a73-72f9308f84a0.JPG)

**Comment by danieljcode** [comment]
Done in my last commit!
