### ISSUE TITLE
Lengthy Projection duration

### ISSUE THREAD

**Issue by imbipulkumar** [danieljcode/COVID-19tracker#16]
• 2 weeks projections cram the 50% of page
• Control should be given to users / visitors to choose the projection period
• This will make the intent of displaying graph more achievable (user engagement)

**Comment by danieljcode** [comment]
https://danieljcode.github.io/COVID-19tracker/ Check the new setup now... It doesn't let the user choose how many projections they want to see but it makes the page seem more populated I hope.
![image](https://user-images.githubusercontent.com/70861451/95743950-79001200-0c8a-11eb-9b80-171a48145590.png)

**Comment by imbipulkumar** [comment]
> https://danieljcode.github.io/COVID-19tracker/ Check the new setup now... It doesn't let the user choose how many projections they want to see but it makes the page seem more populated I hope.
> ![image](https://user-images.githubusercontent.com/70861451/95743950-79001200-0c8a-11eb-9b80-171a48145590.png)

Hey @danieljcode , Looks beautiful now BUT you have induced regression in the footer section. 
Have a look.

**Comment by danieljcode** [comment]
I'm not sure what you mean? all looks ok to me, could you describe the problem a bit more

**Comment by imbipulkumar** [comment]
I mean add footer for a uniform link.

**Comment by danieljcode** [comment]
Ah right ok cool! I'll get on that later today and let you know how it goes!

**Comment by danieljcode** [comment]
![image](https://user-images.githubusercontent.com/70861451/95789474-7ecf1500-0cd5-11eb-8df4-571178660ff3.png)
@imbipulkumar I have finished the footer! 👍🏼
