### ISSUE TITLE
Website Columns issue

### ISSUE THREAD

**Issue by sqwyer** [danieljcode/COVID-19tracker#18]
# Columns Issue

Hey! I was checking the page and I noticed that there is a bit of a columns issue. I am currently using the latest stable release of Firefox, so this could be a Firefox browser thing.

## The Issue

So when I check the page, the columns on the left of the page span much more than they should in height, but the width is normal. I believe the issue is that when the second column was added and adjusted to have more items, the height of the column class was adjusted, which affected both columns.

## Solution

Instead of modififyng the height using the class, I think the second column (right column) should have a second class or ID that has the new height as well as reverting the normal column height to however it was before the change.

**Comment by khushali77** [comment]
Can you show a mockup like how it was earlier?

**Comment by danieljcode** [comment]
I could do with a video or some screenshots of this problem? I think I know what your on about but I wanna be sure :D :)

**Comment by terrifricker** [comment]
I see it in Safari 14.0
![Screen Shot 2020-10-13 at 12 31 46 PM](https://user-images.githubusercontent.com/51532684/95907409-56383100-0d50-11eb-9342-9f8af20c92cf.png)

**Comment by danieljcode** [comment]
I had that bug a couple of times when developing the site, it fixed itself when I refreshed so I thought it wasn't an issue or maybe I'd inadvertently fixed it...

**Comment by sqwyer** [comment]
It appears the issue has been fixed, I believe the issue had to do with `box-sizing: border-box` and possible interference with a BootstrapCSS class called `box` as well as the custom `box` class.
