### ISSUE TITLE
Adding a mobile friendly view for the website

### ISSUE THREAD

**Issue by vieee** [danieljcode/COVID-19tracker#4]
- The app does not have a responsive behaviour when viewed on tablets/mobile devices.

![2020-10-06](https://user-images.githubusercontent.com/47855729/95215199-572c0880-080e-11eb-861e-cf90d027ad34.png)

If you do feel this is an issue, I would love to contribute to it..

**Comment by vieee** [comment]
I would love to take up this issue, could I..?

**Comment by danieljcode** [comment]
Oh damn, It used to have one when I originally developed it but i've since merged some pull requests that changed the design, The changes look good on desktop but I didn't check mobile before merging so partly my fault... :/

**Comment by danieljcode** [comment]
> I would love to take up this issue, could I..?

Yeah of course shouldn't be too hard! just set the two side by side divs to be 100% width when the screen size is less than a certain amount of pixels... use a media quest @media(max-width: 800px){ CSS HERE }

**Comment by ptrandev** [comment]
I addressed a few of these in #5 and will continue to do so in upcoming pull requests.

**Comment by danieljcode** [comment]
> I addressed a few of these issues in #5 and will continue to do so in upcoming pull requests. I recommend relying upon Boostrap's grid system, which makes it easier to construct a responsive site.

Great to know! Thanks for contributing :D :)
