### ISSUE TITLE
New style for "contributors" section (legacy version)

### ISSUE THREAD

**Issue by h-shams** [danieljcode/COVID-19tracker#52]
**Is your feature request related to a problem? Please describe.**
contributors section just have links to Github accounts

**Describe the solution you'd like**
changing style to showing avatar and name of the contributors instead of only links.

**Describe alternatives you've considered**
we can send a request to api.github.com to get information about contributors (including avatar URL and name of the contributor) and use that information to change UI.
This is an example
![Capture](https://user-images.githubusercontent.com/38860648/97070824-4a6a2b80-15e8-11eb-876f-a2e4939ea78a.PNG)

**Additional context**
Nothing 😄

**Comment by danieljcode** [comment]
A similar system is in place currently (added by a contributor) it shows names and profile photos it just doesnt query the github API...

**Comment by h-shams** [comment]
That's great 😄, thanks for responding

**Comment by danieljcode** [comment]
> That's great 😄, thanks for responding

No problem 👍🏼
