### ISSUE TITLE
Two Week Projections UI Issue

### ISSUE THREAD

**Issue by lemuellloren** [danieljcode/COVID-19tracker#7]
Hello Daniel I saw the COVID 19 tracker website, it has UI issue on Two Week Projections section box are not displayed properly. Can I fix it for you?

**Comment by danieljcode** [comment]
Could you describe this issue in more detail? I just had a look at the mobile and desktop versions of the site and they seem to be ok, maybe I missed it 😆 🤣

**Comment by danieljcode** [comment]
Since I see no issue with the UI, it's been two days and you haven't replied I'm going to close this issue now.
